In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/DhruvBhirud/datasets/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [3]:
df

Unnamed: 0  Clothing ID  Age  \
0               0          767   33   
1               1         1080   34   
2               2         1077   60   
3               3         1049   50   
4               4          847   47   
...           ...          ...  ...   
23481       23481         1104   34   
23482       23482          862   48   
23483       23483         1104   31   
23484       23484         1084   28   
23485       23485         1104   52   

                                                   Title  \
0                                                    NaN   
1                                                    NaN   
2                                Some major design flaws   
3                                       My favorite buy!   
4                                       Flattering shirt   
...                                                  ...   
23481                     Great dress for many occasions   
23482                         Wish it was made of cotton   
23483                              Cute, but see through   
23484  Very cute dress, perfect for summer parties an...   
23485                    Please make more like this one!   

                                             Review Text  Rating  \
0      Absolutely wonderful - silky and sexy and comf...       4   
1      Love this dress!  it's sooo pretty.  i happene...       5   
2      I had such high hopes for this dress and reall...       3   
3      I love, love, love this jumpsuit. it's fun, fl...       5   
4      This shirt is very flattering to all due to th...       5   
...                                                  ...     ...   
23481  I was very happy to snag this dress at such a ...       5   
23482  It reminds me of maternity clothes. soft, stre...       3   
23483  This fit well, but the top was very see throug...       3   
23484  I bought this dress for a wedding i have this ...       3   
23485  This dress in a lovely platinum is feminine an...       5   

       Recommended IND  Positive Feedback Count   Division Name  \
0                    1                        0       Initmates   
1                    1                        4         General   
2                    0                        0         General   
3                    1                        0  General Petite   
4                    1                        6         General   
...                ...                      ...             ...   
23481                1                        0  General Petite   
23482                1                        0  General Petite   
23483                0                        1  General Petite   
23484                1                        2         General   
23485                1                       22  General Petite   

      Department Name Class Name  
0            Intimate  Intimates  
1             Dresses    Dresses  
2             Dresses    Dresses  
3             Bottoms      Pants  
4                Tops    Blouses  
...               ...        ...  
23481         Dresses    Dresses  
23482            Tops      Knits  
23483         Dresses    Dresses  
23484         Dresses    Dresses  
23485         Dresses    Dresses  

[23486 rows x 11 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [5]:
df.describe()

Unnamed: 0   Clothing ID           Age        Rating  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean   11742.500000    918.118709     43.198544      4.196032   
std     6779.968547    203.298980     12.279544      1.110031   
min        0.000000      0.000000     18.000000      1.000000   
25%     5871.250000    861.000000     34.000000      4.000000   
50%    11742.500000    936.000000     41.000000      5.000000   
75%    17613.750000   1078.000000     52.000000      5.000000   
max    23485.000000   1205.000000     99.000000      5.000000   

       Recommended IND  Positive Feedback Count  
count     23486.000000             23486.000000  
mean          0.822362                 2.535936  
std           0.382216                 5.702202  
min           0.000000                 0.000000  
25%           1.000000                 0.000000  
50%           1.000000                 1.000000  
75%           1.000000                 3.000000  
max           1.000000               122.000000

In [6]:
df.shape

(23486, 11)

In [7]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [8]:
df[df['Review Text']==""]=np.NaN

In [9]:
df['Review Text'].fillna("No Review", inplace = True)

In [10]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [11]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

In [12]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [13]:
X = df['Review Text']

In [14]:
y = df['Rating']

In [15]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify=y, random_state = 12529) 

In [18]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features = 5000)

In [21]:
X_train = cv.fit_transform(X_train)

In [22]:
cv.get_feature_names_out()

array(['0p fit', '10 10', '10 12', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [23]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
X_test = cv.fit_transform(X_test)

In [25]:
cv.get_feature_names_out()

array(['10 12', '10 fit', '10 got', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [26]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
model = MultinomialNB()

In [29]:
model.fit(X_train, y_train)

MultinomialNB()

In [30]:
y_pred = model.predict(X_test)

In [31]:
y_pred.shape

(7046,)

In [32]:
y_pred

array([5., 1., 5., ..., 3., 4., 4.])

In [33]:
model.predict_proba(X_test)

array([[0.05195875, 0.08260154, 0.17570434, 0.22106802, 0.46866734],
       [0.36050981, 0.05009674, 0.11403525, 0.15638324, 0.31897497],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.05656578, 0.02108659, 0.48254844, 0.02343763, 0.41636156],
       [0.01070241, 0.00656414, 0.00939201, 0.92843325, 0.04490819],
       [0.03736085, 0.04541674, 0.05181356, 0.4371705 , 0.42823834]])

In [34]:
from sklearn.metrics import confusion_matrix, classification_report

In [35]:
print(confusion_matrix(y_test, y_pred))

[[  18   28   29   48  130]
 [  60   40   46  102  222]
 [ 101   86  100  185  389]
 [ 191  161  166  321  684]
 [ 421  401  355  788 1974]]


In [36]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.03       253
         2.0       0.06      0.09      0.07       470
         3.0       0.14      0.12      0.13       861
         4.0       0.22      0.21      0.22      1523
         5.0       0.58      0.50      0.54      3939

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046



In [37]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [38]:
df.replace({'Rating': {1:0, 2:0, 3:0, 4:1, 5:1}}, inplace = True)

In [39]:
y = df['Rating']

In [40]:
X = df['Review Text']

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify=y, random_state = 12529) 

In [43]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [45]:
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features = 5000)

In [46]:
X_train = cv.fit_transform(X_train)

In [47]:
X_test = cv.fit_transform(X_test)

In [48]:
from sklearn.naive_bayes import MultinomialNB

In [49]:
model = MultinomialNB()

In [50]:
model.fit(X_train, y_train)

MultinomialNB()

In [51]:
y_pred = model.predict(X_test)

In [52]:
y_pred.shape

(7046,)

In [53]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

In [54]:
from sklearn.naive_bayes import MultinomialNB

In [55]:
model = MultinomialNB()

In [56]:
model.fit(X_train, y_train)

MultinomialNB()

In [57]:
y_pred = model.predict(X_test)

In [58]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

In [59]:
y_pred.shape

(7046,)

In [60]:
from sklearn.metrics import confusion_matrix, classification_report

In [61]:
print(confusion_matrix(y_test, y_pred))

[[ 326 1257]
 [1038 4425]]


In [62]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.24      0.21      0.22      1583
         1.0       0.78      0.81      0.79      5463

    accuracy                           0.67      7046
   macro avg       0.51      0.51      0.51      7046
weighted avg       0.66      0.67      0.67      7046

